FROM ubuntu:22.04
RUN apt-get update

# Building GCC
RUN apt-get update && apt-get install -y \
    build-essential \
    gcc-10 g++-10 gfortran-10 curl make libnuma-dev libnl-3-200 autoconf
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 7 && \
    update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 7 && \
    update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-10 7
RUN apt-get install --yes wget vim git

# Building MPICH3
RUN mkdir /software /build
WORKDIR /build
RUN wget https://www.mpich.org/static/downloads/3.3.2/mpich-3.3.2.tar.gz
RUN tar xvf mpich-3.3.2.tar.gz
WORKDIR mpich-3.3.2
RUN ./configure FFLAGS=-fallow-argument-mismatch
RUN make -j 8 VERBOSE=1
RUN make install

WORKDIR /
RUN rm -rf /build 
RUN ldconfig 
ENV LD_LIBRARY_PATH="/usr/lib:/usr/local/lib:${LD_LIBRARY_PATH}"

