FROM krccl/openmpi_base:403
RUN apt-get update && apt-get install -y git autoconf libaec-dev \
            libjpeg8-dev libcairo2-dev libpango1.0-dev python3-jinja2 libboost-dev \
            libcairo2-dev libpango1.0-dev python3-jinja2 libboost-dev libgrib-api-dev \
            libxml2-dev libcurl4-gnutls-dev
ENV PATH /software/bin:$PATH
ENV LD_LIBRARY_PATH /software/lib:$LD_LIBRARY_PATH
ENV PKG_CONFIG_PATH /software/lib/pkgconfig:$PKG_CONFIG_PATH
WORKDIR /software
RUN git clone -b v1.2.11 https://github.com/zlib-ng/zlib-ng.git && \
    cd zlib-ng && \
    ./configure --prefix=/software --sharedlibdir=/software/lib && \
    make && make install && \
    cd /software && \
    git clone -b hdf5-1_12_2 https://github.com/HDFGroup/hdf5.git && \
	cd hdf5 && \
    ./configure --prefix=/software --enable-parallel --with-zlib=/software && \
    make VERBOSE=1 && make install && \
	cd /software && \
    curl https://parallel-netcdf.github.io/Release/pnetcdf-1.12.3.tar.gz -o /tmp/pnetcdf-1.12.3.tar.gz && \
    tar xvf /tmp/pnetcdf-1.12.3.tar.gz && \
    cd pnetcdf-1.12.3 && \
    ./configure --prefix=/software --enable-shared  && \
    make VERBOSE=1 && make install  && \
    cd /software && \
    git clone -b v4.9.0 https://github.com/Unidata/netcdf-c.git && \
    cd /software/netcdf-c && \
    autoconf && \
    ./configure --enable-pnetcdf --with-pic --enable-shared --prefix=/software CPPFLAGS=-I/software/include LDFLAGS=-L/software/lib LIBS=-lz && \
    make && make install && \
	cd /software && \
    curl -L https://github.com/Kitware/CMake/releases/download/v3.24.0/cmake-3.24.0-linux-x86_64.sh -o /tmp/cmake-3.24.0-linux-x86_64.sh && \
    sh /tmp/cmake-3.24.0-linux-x86_64.sh --prefix=/software --skip-license 
RUN rm -rf zlib-ng hdf5 pnetcdf-1.12.3 netcdf-c /tmp/*

# Installing CDO dependencies
WORKDIR /software
RUN apt-get install -y unzip && \
    curl -L http://www.ece.uvic.ca/~mdadams/jasper/software/jasper-1.900.1.zip -o /tmp/jasper-1.900.1.zip && \
    unzip /tmp/jasper-1.900.1.zip && \
    cd jasper-1.900.1 && \
    ./configure --prefix=/software --enable-shared && \
    make VERBOSE=1 && make install && \
	cd  /software && \
    curl -L https://confluence.ecmwf.int/download/attachments/45757960/eccodes-2.26.0-Source.tar.gz -o /tmp/eccodes-2.26.0-Source.tar.gz && \
    tar xvf /tmp/eccodes-2.26.0-Source.tar.gz && \
    mkdir build-eccodes && cd build-eccodes && \
    cmake -DCMAKE_INSTALL_PREFIX=/software \
          -DENABLE_ECCODES_THREADS=OFF -DENABLE_ECCODES_OMP_THREADS=ON \
          ../eccodes-2.26.0-Source  && \
    make VERBOSE=1 && make install && \
	cd /software && \
	curl -L https://download.osgeo.org/proj/proj-5.0.1.tar.gz -o /tmp/proj-5.0.1.tar.gz && \
    tar xvf /tmp/proj-5.0.1.tar.gz && \
    cd proj-5.0.1 && ./configure --prefix=/software && make && make install && \
    cd /software && \
    curl -L https://confluence.ecmwf.int/download/attachments/3473464/Magics-4.0.3-Source.tar.gz -o /tmp/Magics-4.0.3-Source.tar.gz && \
    tar xvf /tmp/Magics-4.0.3-Source.tar.gz && \
    mkdir build-magics && cd build-magics && \
    cmake -DCMAKE_INSTALL_PREFIX=/software -Deccodes_DIR=/software -DPROJ4_PATH=/software \
    -DCMAKE_CXX_FLAGS='-fPIC -include limits' -DECCODES_LIBRARIES='-L/software/lib -leccodes ' \
    ../Magics-4.0.3-Source/ && \
    make VERBOSE=1 && make install

#Install CDO
WORKDIR /software
ENV NETCDF_DIR /software
ENV NC_CONFIG /software/bin/nc-config
ENV HDF5_DIR /software

COPY patch.grid_proj.cc /software
RUN curl -L https://code.mpimet.mpg.de/attachments/download/24638/cdo-1.9.10.tar.gz -o /tmp/cdo-1.9.10.tar.gz && \
    tar xvf /tmp/cdo-1.9.10.tar.gz && \
    cd cdo-1.9.10 && \
    patch -p 0 -p 0 src/mpim_grid/grid_proj.cc /software/patch.grid_proj.cc && \
    ./configure --prefix=/software  --with-netcdf=$NETCDF_DIR --with-magics=/software --with-eccodes=/software \
    --with-hdf5=/software --with-proj=/software --with-fftw3 --with-curl --with-libxml2 --with-grib_api --enable-netcdf4 && \
    make VERBOSE=1 && make install

WORKDIR /software    
RUN rm -rf jasper-1.900.1 build-eccodes build-magics  \
		   /software/patch.grid_proj.cc \
           eccodes-2.26.0-Source proj-5.0.1 \
           Magics-4.0.3-Source /tmp/*
