FROM krccl/mpich_base:332

#Building OSU microbenchmarks 5.6.3
RUN curl -o /tmp/osu-micro-benchmarks-5.6.3.tar.gz http://mvapich.cse.ohio-state.edu/download/mvapich/osu-micro-benchmarks-5.6.3.tar.gz
RUN tar xvf /tmp/osu-micro-benchmarks-5.6.3.tar.gz -C /tmp
WORKDIR /tmp/osu-micro-benchmarks-5.6.3
RUN CC=mpicc CXX=mpicxx ./configure --prefix=/usr/local
RUN make -j 8 VERBOSE=1
RUN make install
WORKDIR /
RUN rm -rf /tmp/osu-micro-benchmarks-5.6.3.tar.gz /tmp/osu-micro-benchmarks-5.6.3
